name: Deploy to staging

on:
  push: 
    branches:
      - main

jobs:
  redeploy-everything:
    name: Deploy everything to staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ssh key
        run: | 
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/subratjan.pem
          chmod 600 ~/.ssh/subratjan.pem

      - name: Deploy to EC2 
        run: | 
            ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/subratjan.pem ubuntu@3.93.177.150 << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            node -v
            bun -v
            pm2 -v 

            cd aws-cicd
            git pull origin main
            bun install
            pm2 restart aws-cicd
            EOF